# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Second Issue Test
on:
  schedule:
    - cron: 30 11,23 * * *

jobs:
  create_issue:
    name: Create second issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3.4.1
        with:
          assignees: "mghpcsim"
          labels: "test"
          title: "Second issue"
          body: |
            ### Agenda

            - [ ] task 5
            - [ ] task 6
            - [ ] task 7
            - [ ] task 8
                    
            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/mghpcsim/issuetest/wiki)
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
